### PR TITLE
Update conferences.yml - EACL 2024

### PR DESCRIPTION
**Pull request by yuvalpinter**
Added EACL 2024

### CODE REVIEW

**Comment by andrewkuanop** [comment]
The URL seems to wrong.

**Comment by yuvalpinter** [comment]
The site isn't up yet, but that's where it will eventually be.

- Yuval

**Comment by yuvalpinter** [comment]
Can someone please merge this? @abhshkdz ?

**Comment by andrewkuanop** [comment]
Hey @yuvalpinter, I understand that that's where it'll eventually be but we prefer giving the best information to the users. Please create another pull request when the site is up. Thanks.

**Comment by yuvalpinter** [comment]
So you'd rather than a deadline that's three months away won't be on the website? How is this "the best information"? I don't get it.

**Comment by yuvalpinter** [comment]
Reopened as #575 without the URL, even though this helps absolutely nobody.

**Pull request closed without merging**
