### PR TITLE
Add navbar and new dropdown filter

### PR DESCRIPTION
**Pull request by a-nau**
This implements some of the features suggested in Issue #405:

- [x] Add tab at the top for cleaner look
  - upgrade to Bootstrap v4
  - use Bootstrap navbar
  - restructure by using `_includes`
- [x] Add subject filter at the top to more easily select conferences (default: all conferences selected)
  - change filter to dropdown to allow easy (un-)select all
  - Note that the old filtering method is not compatible with the new Bootstrap (but this could be fixed)

Some open questions and comments:
- Is the PwC logo sufficient or should we add a link/pointer to Papers With Code?
- Do you think it makes sense to have an extra page (i.e. link in navbar) that links to other useful resources, similar to the `readme.md`?
- What do you think about the restructuring? 
- There is some misalignments on the conference details page, which will be fixed upon merge with #409

Looking forward to your feedback! :)

### CODE REVIEW

**Comment by omarsar** [comment]
Hi @a-nau . Thanks for this new PR. I will look into this next week.

**Comment by omarsar** [comment]
Hi @a-nau just got a chance to look into the PR. Because we did changes in previous PR, some things got broken here. Are you able to check the conflicts and make sure issues are resolved before I can review. I can also do it but I guess because you did changes it will be much easier for you to spot conflicts.

**Comment by a-nau** [comment]
Hi @omarsar, sorry this week has been quite busy. Sure, I agree it's easiest if I quickly resolve the issues. I'll ping you when it's done.

**Comment by a-nau** [comment]
Hi @omarsar, I merged the two branches. Looking forward to your feedback!

**Comment by omarsar** [comment]
Hi @a-nau Thanks for this PR. Great work. 
Here is some feedback from the team:

1) We like "by Papers with Code" to be included like the example below. It doesn't have to be exact.
2) The filter select doesn't seem to be aligned well (vertically speaking), same with the "Tweet" and Github buttons in the navbar (not properly aligned horizontally).

I think with those two fixes, this PR looks good. Really love how it's coming out. Have a great weekend. :)

image

**Comment by a-nau** [comment]
Hi @omarsar, thanks for your feedback! The idea of adding the PwC link in the navbar is very good :) 
Alignment should be better now. Let me know if you find any issues.

**Comment by omarsar** [comment]
@a-nau the header looks great! Minor comments:

- I notice that the GitHub star button doesn't show number of stars anymore. Maybe something broke accidentally or it could be my environment.
- Maybe not obvious for me, but the filter is centred right?

image

- The social buttons look weird in mobile mode for front page:
image

and conference page:

image

Thanks for all the work so far.

**Comment by a-nau** [comment]
Hi @omarsar,

thanks for the feedback! However, I cannot reproduce the errors you see. I tried Chrome and Firefox with a bunch of random resolutions, but it looks fine. Not sure what the issue could be here. Which browser and resolution did you use?

- I noticed one issue with loading the Twitter button in the navbar on mobile 
  - grafik
- The alignment of the filter seems a tiny bit off, now that you mention it. "Perfect" alignment would mean both texts are on the exact same line, wouldn't it?

**Comment by omarsar** [comment]
Hi @a-nau 
> 
> thanks for the feedback! However, I cannot reproduce the errors you see. I tried Chrome and Firefox with a bunch of random resolutions, but it looks fine. Not sure what the issue could be here. Which browser and resolution did you use?
> 
> * I noticed one issue with loading the Twitter button in the navbar on mobile
>   
>   * grafik
> * The alignment of the filter seems a tiny bit off, now that you mention it. "Perfect" alignment would mean both texts are on the exact same line, wouldn't it?

I'm using Chrome. It happens regardless of the device I select. Could be my machine.
image

I tried it with Firefox and Safari and it looks okay there. So it could be my current browser. 

As for the alignment of filter, I think it's good the way it is. Not a big deal to be honest.  

Are you happy to merge this? Or you plan any further modifications?

**Comment by a-nau** [comment]
I would say you can merge it. I'll check the alignment and try to look into the issue I found during the next PR. Really looking forward to seeing the calendar online :)

**Pull request merged**
