### PR TITLE
Add icon-based link overview and update conference details

### PR DESCRIPTION
**Pull request by a-nau**
This implements some of the features suggested in [Issue #405](https://github.com/paperswithcode/ai-deadlines/issues/405):
- [x] Reformatting conference page details
  - use icons to display key information
  - add a subject badge (similar to main page)
  - added the calendar download button from the overview page here too
- [x] Accessible links: The main idea is to have additional accessible links for each conference right from the front page.
  - use icons for all links and show all relevant links next to conference name
  - Link from conference name is removed

Further changes/comments:
- [IcoMoon Icons](https://icomoon.io/#icons-icomoon) are used (see readme)
- added a smaller timer for mobile devices (since icons for link need space)

Hope this helps & looking forward to feedback!

### CODE REVIEW

**Comment by omarsar** [comment]
Hey @a-nau 

This is looking great. I like the use of icons. 

Here are some comments:
1. The conference page looks good to me. 
2. On the front page, the icons break to new line when conference line is too long (see image below). This happens when browsing through mobile view. I wonder if it makes more sense to have them in new line. 
3. What if we were to just use the original conference name as link instead of the `( i )` icon. I think the rest of icons all point to external links so it may be confusing for users. The main idea: the main link is the conference name and then all other links are the icons. Thoughts?
4. The icons have a weird line underneath. I guess all links have same style but it stands out a lot more with the icons. 
5. Now that the links are the icons, do you think the icons stand out enough? 

Looking forward to your thoughts. 

image

image

**Comment by a-nau** [comment]
Thanks for the feedback @omarsar !
- regarding (3): removing the ℹ️  is a good idea I think. Sounds good to keep the internal link on the conference name and only use icons for external links. I'll change that.
- regarding (4)+(5): I left the underline below the icons to hint on the fact that they are links. On desktop I think it's less of an issue, since more information is shown on hover, however, on mobile it's indeed a bit difficult. If icons move to a new line, there might be space to put "Links: 🌍📚 ..."? Do you think that would be better?
- regarding (2): I haven't extensively tested different screen resolutions, but you're right - doesn't look too good. Moving the icons to a new line for mobile sounds good. Also we could split space for the left/right side 50:50 and not 5:7 as it is now?

**Comment by omarsar** [comment]
Hi @a-nau 

"regarding (4)+(5): I left the underline below the icons to hint on the fact that they are links. On desktop I think it's less of an issue, since more information is shown on hover, however, on mobile it's indeed a bit difficult. If icons move to a new line, there might be space to put "Links: 🌍📚 ..."? Do you think that would be better?"

In that case it might be okay to go with what you have now. All in one line. 

"regarding (2): I haven't extensively tested different screen resolutions, but you're right - doesn't look too good. Moving the icons to a new line for mobile sounds good. Also we could split space for the left/right side 50:50 and not 5:7 as it is now?

Agreed. Just try a few thing and let's go with what you think is best. 

Awesome! Looking forward to the changes. Thanks.

**Comment by a-nau** [comment]
Hi @omarsar,

I played around a bit and made the following changes
- remove the ℹ️ icon and use the conference names as link instead
- always use a 50:50 split between conference info and deadline counter (gives us some more space)
- icons always move together, i.e. if there is space they are shown in the same line as the conference name and if there is not enough space to display all icons, they move together to a new line

Do you think that's better now?

**Comment by omarsar** [comment]
Hi @a-nau thanks for the revisions. This looks a lot better. 
One minor thing I noticed with the current events:

When icon goes to next line, there is no spacing between text and icon.

image

In the Past Events section, this doesn't happen though. Not sure what's the issue. 

image

**Comment by a-nau** [comment]
Hi @omarsar,

thanks for the feedback, I overlooked that. I solved the issue in a somewhat hacky way by adding `&ZeroWidthSpace;`s. I experienced different behaviour in Firefox and Chrome and am not sure how we could solve this more elegantly. Also, I adjusted formatting, since Firefox seemed to misinterpret it otherwise (by adding unwanted whitespaces).

In my tests this solutions worked fine for now. Please let me know if there is still any unexpected behavior.

**Comment by omarsar** [comment]
Hi @a-nau Looks great! I am merging this and moving to the to other PR. Thanks.

**Comment by a-nau** [comment]
Perfect, thanks @omarsar!

**Pull request merged**
