### PR TITLE
Add calendar overview for deadlines and conference dates

### PR DESCRIPTION
**Pull request by a-nau**
This implements the calendar feature suggested in Issue #405:

- [x] Adding Calendar tab: Add a calendar where all the events can be accessed
  - added new fields to the yaml and changed formatting a bit (thus a big diff in the file); see example in readme
  - added calendar with same filtering functionality into a new tab
  - restructure a bit: move `home.html` to `index.html`
- Some other adjustments
  - added the option to provide a full conference name (display on hover in overview and second headline on conference page)
  - adjusted some inconsistent conference data
  - removed the `Note` from the `yaml`, now every note automatically starts with **Note:**
  - add Google Maps link also to conference details page

Some open questions and comments:
- I ignored some recent changes (i.e. added conferences) since the diff is very big in the `conferences.yml` and easy merging was not possible. Before merging this, we should check this to not lose information.
- I noticed that some conferences are overwritten instead of added. Is this desired? Of course, a huge history is not needed but especially with features like published papers and PwC link it makes sense to not overwrite it the next year, doesn't it?
- The issue with limited calendar usability for the mobile version remains: Data is displayed on hover, which is not possible on mobile.

Looking forward to your feedback! :)

### CODE REVIEW

**Comment by omarsar** [comment]
@a-nau thanks for this PR. I will check it soon and provide some feedback.

**Comment by omarsar** [comment]
Some feedback regarding this new additions and changes:

> "I ignored some recent changes (i.e. added conferences) since the diff is very big in the conferences.yml and easy merging was not possible. Before merging this, we should check this to not lose information."

We can definitely check before merging. 

> "I noticed that some conferences are overwritten instead of added. Is this desired? Of course, a huge history is not needed but especially with features like published papers and PwC link it makes sense to not overwrite it the next year, doesn't it?"

Yes, I will need to provide some instruction to make this clear that this is the direction we want to go. The idea is to have a history and potentially reuse that data for some other future features. Not a big priority in my opinion but we can try encourage people to not overwrite. 

> "The issue with limited calendar usability for the mobile version remains: Data is displayed on hover, which is not possible on mobile."

Yeah, it will be limited in mobile if we proceed with current state. However, if it is too much work to improve, then the current state should be fine for mobile. The only concern, and this applies to the desktop view as well, is that if there are multiple conferences on the same day (ie. overlap) it can be confusing how it picks where to go. But on second thought, maybe it's not too big of a deal if you already get a quick preview upon hovering. 

BTW, I got confused about the data in the example below. It might help if we can provide some kind of color clue in the hover info (e.g., make MM2022 display red and CHIL 2022 display yellow). Not sure to be honest but the overlapping data can be a bit confusing. Maybe you have some ideas here?

image

Those are my initial thoughts. The other suggested changes are fine by me. If we can find a way to improve the calendar desktop view a bit more, in particular when it overlaps, it would be great. Otherwise, this looks good to me.

**Comment by a-nau** [comment]
Thanks for the feedback!

- The selection/mobile issue is of course something we can look into. But I am not sure how easy it is to fix. The search that I implemented on [my version](https://deadlines.info) might also help to alleviate that issue a bit? If you can check the calendar and then search for the conference?
- Making deadlines red is no issue at all, however, as far as I can tell we would need to move colors from the `yaml` to the `css` file to show the respective subject colors on hover. Also, my idea here was to underline in the respective color, so it's not that strong. You can check [my version](https://deadlines.info) of the site, there I changed the font of deadlines to red.
-  Regarding the date formatting: I thought about it again and `MM/DD/YYYY` is a rather confusing date format (at least for me ;)). Maybe it's best to stick with the `YYYY-MM-DD HH:MM` format (omitting seconds)? The only thing that I don't like about it is that `yaml` needs `'` around this date format, `YYYY/MM/DD HH:MM` would work without these.

**Comment by omarsar** [comment]
Hi @a-nau 

> The selection/mobile issue is of course something we can look into. But I am not sure how easy it is to fix. The search that I implemented on [my version](https://deadlines.info/) might also help to alleviate that issue a bit? If you can check the calendar and then search for the conference?

I think search could help more broadly but I think it should be a separate feature to work on. If you are happy with the current state of the calendar in both desktop and mobile view we are okay to proceed with merging it. Let's treat the feature as experimental for now and if there are complaints on the usability or suggestions to improve, then we can always improve it later on. I think the feature is already very useful in the current state. 

> Making deadlines red is no issue at all, however, as far as I can tell we would need to move colors from the yaml to the css file to show the respective subject colors on hover. Also, my idea here was to underline in the respective color, so it's not that strong. You can check [my version](https://deadlines.info/) of the site, there I changed the font of deadlines to red.

You are right about that. If it will not scale so well or it's a bit too tedious to manage, I think the current state is fine as well (i.e. without font colors). Which do you prefer, color or without color?

> Regarding the date formatting: I thought about it again and MM/DD/YYYY is a rather confusing date format (at least for me ;)). Maybe it's best to stick with the YYYY-MM-DD HH:MM format (omitting seconds)? The only thing that I don't like about it is that yaml needs ' around this date format, YYYY/MM/DD HH:MM would work without these.

I also agree that the current date formatting is confusing but I think this could be tricky to change now. If the people contributing to the yaml file complain about this, then we should consider changing. If no one is complaining, maybe it's not that important to change it now. In fact, we can always do this entirely ourselves as part of a scheduled maintenance if there are benefits from development standpoint.

**Comment by a-nau** [comment]
Hi @omarsar,

Ok, thanks for the feedback, sounds good :) I will update:
- Underline deadlines in red
- Check date formats and adjust it back to `YYYY-MM-DD HH:MM` 
- Check the missing recent conferences

After that, I think we are good to go and handle other features in another PR, as you said.

**Comment by a-nau** [comment]
Hi @omarsar, sorry it took longer than expected to find the time, although it were rather minor changes. Now changes are ready to merge if you don't spot any issues :)

**Comment by omarsar** [comment]
Hi @a-nau,

This is great! All looks good to me. Thank you for the PR.

**Pull request merged**
