### PR TITLE
Change process.py so it ends in a newline

### PR DESCRIPTION
**Pull request by bryant1410**
Hey, I noticed that when I submit a change (a PR) through GitHub it always adds a newline at the end of the file, [like in the last PR I sent](https://github.com/abhshkdz/ai-deadlines/pull/216/files#diff-db4cb6c5b8f3c23a1908911314ea4160L447). I'm proposing this change to still make the information be separated by a newline but by making it end with the new line instead of starting with the newline.

The resulting file shouldn't have an empty line at the beginning anymore but now at the end.

### CODE REVIEW

**Comment by bryant1410** [comment]
Btw, I wonder how is the auto-commit set up.

**Comment by abhshkdz** [comment]
The auto-commit is fairly hacky: it runs process.py + commit + push on a cron-job :)

**Comment by bryant1410** [comment]
Oh :smile: GitHub Actions seems to support this use-case if you're interested one day in a fancier solution: https://github.com/cds-snc/github-actions/tree/master/auto-commit Or you could also make Travis to auto-commit after it's merged.

**Comment by abhshkdz** [comment]
GitHub Actions looks cool! Thanks for the pointer! I might set it up one of these days :)

**Pull request merged**
